# Default Workflow: Plan → Implement → Review → Finalize
#
# Flow: plan → implement → review → finalize → end
#       └────────────────────┘ (loop on REJECTED)

name: default

steps:
  plan:
    prompt: |
      Analyze the task and create an implementation plan.
      Write the plan as a structured document.
      End with <!-- DECISION: PLANNED -->
    next:
      - if: PLANNED
        goto: implement
      - goto: plan

  implement:
    prompt: |
      Read .jdi/reports/{task_id}/plan.md and implement the plan.
      End with <!-- DECISION: IMPLEMENTED -->
    next:
      - if: IMPLEMENTED
        goto: review
      - goto: implement

  review:
    prompt: |
      Read .jdi/reports/{task_id}/implement.md and review the implementation.
      End with <!-- DECISION: APPROVED --> or <!-- DECISION: REJECTED -->
    next:
      - if: APPROVED
        goto: finalize
      - if: REJECTED
        goto: implement
      - goto: implement

  finalize:
    prompt: |
      Finalize the implementation. Clean up any loose ends.
    next:
      - goto: end
